### ISSUE TITLE
Unlocking old locks failed: etcd.service is inactive for endpoint on other host

### ISSUE THREAD

**Issue by zjeraar** [coreos/locksmith#59]
When I configure an etcd endpoint on another host and etcd is not running on the locksmith host, I get the message:

Unlocking old locks failed: etcd.service is inactive.

**Comment by xueshanf** [comment]
You probably ran into the same issue [#66](https://github.com/coreos/locksmith/issues/66). The endpoint is working for locksmithctl client if you point the endpoint to the cluster's etcd server,  but not the daemon.

**Comment by benkershner** [comment]
Yeah, seeing this same issue. The difference between this and #66 is that I do *not* want etcd running on my worker nodes, so relying on the local service being up and then calling out to the central services is a little scary.

**Comment by jonboulle** [comment]
@benkershner the intention is indeed that you don't need to run etcd on every node. The root cause here is that unfortunately the release is lagging the docs; this flag will only work on 0.2.3+ which has not yet made it into CoreOS alpha. Expect it to arrive within the next week.
