### ISSUE TITLE
 Unknown strategy: off

### ISSUE THREAD

**Issue by apognu** [coreos/locksmith#68]
Hi there,

I don't know if the docs on CoreOS's website are outdated, but the "off" reboot strategy for locksmithd is not recognized (anymore). Here's what I'm getting in my logs:

```locksmithd[31365]: Unknown strategy: off```

Has the option been removed? Should the service be disabled for the behavior to be reproduced?

**Comment by crawford** [comment]
Which version of locksmith is this? What reboot strategy does your cloud config use ("off", off, 0, yellow)?

**Comment by apognu** [comment]
Sorry about that, locksmithd v0.2.2 on CoreOS 494.5.0 (stable channel).

Here is my _/etc/coreos/update.conf_:

```
GROUP=stable
REBOOT_STRATEGY=off
```

Do you need any other information?

**Comment by crawford** [comment]
What reboot strategy is listed in your cloud-config?

**Comment by marineam** [comment]
@crawford so if I remember correctly cloudinit handles off by masking locksmith but locksmith itself is unaware of the option. Which would make translating cloudinit instructions to update.conf counterintuitive. I don't think there is a systemd Condition attribute we could use but we could make locksmithd exit and ensure the systemd unit is configured to not restart it.

**Comment by crawford** [comment]
@marineam correct. `REBOOT_STRATEGY=off` does result in the error message originally reported. I'm curious why that option was written to /etc/coreos/update.conf. It might be worth explicitly handling "off" within locksmithd (gracefully exiting).

**Comment by crawford** [comment]
@mischief can you make locksmith gracefully handle `REBOOT_STRATEGY=off`?
