### ISSUE TITLE
daemon: unlock logic does not consider LOCKSMITHD_ENDPOINTS

### ISSUE THREAD

**Issue by jonboulle** [coreos/locksmith#69]
As pointed out by @popsikle in https://github.com/coreos/locksmith/issues/66#issuecomment-77923153:
> on a side note, there seems to be some logic missing for off-host etcd clusters using etcd-lock strat:
https://github.com/coreos/locksmith/blob/master/locksmithctl/daemon.go#L248-L251 will always fail if etcd is masked on the current host because etcd is running on service hosts, not workers.

/cc @crawford

**Comment by paulcichonski** [comment]
Just wondering if there were any plans to fix this? 

We are currently having to manually run `locksmithctl --endpoint=http://$remote-etcd:4001 unlock` against the remote etcd cluster to allow updates to roll through (we are not running etcd in proxy mode on the workers).

**Comment by philips** [comment]
@mischief @jonboulle I am confused where the logic is wrong and the code highlights are wrong against master. Can someone please help show where the code is that needs to be fixed, this sounds like an obvious one.

**Comment by philips** [comment]
I see what needs to happen, essentially we should be using `r.useLock` instead of etcdActive here: https://github.com/coreos/locksmith/blob/master/locksmithctl/daemon.go#L262

@mischief or @crawford can you get a fix together?
