### ISSUE TITLE
Add support for groups

### ISSUE THREAD

**Issue by crawford** [coreos/locksmith#70]
Locksmith should be able to put sets of machines into reboot groups, and those groups should be able to be configured separately. Let's say, for example, I have two load-balancers and ten workers with a static, three-node etcd cluster. I should be able to specify that only one machine from the load-balancing group can reboot at a time, five of the workers can reboot at a time, and only one of the etcd machines can reboot at a time.

**Comment by crawford** [comment]
Fixed by https://github.com/coreos/locksmith/pull/77.

**Comment by devurandom** [comment]
This feature is [documented], but the version this was implemented in is not mentioned. I am running v0.3.0, which is supposed to be the latest version, but it does not support the `-group` parameter to `locksmithctl`.

[documented]: https://github.com/coreos/locksmith/blob/master/README.md#configuring-groups
