### ISSUE TITLE
Support for maintenance windows

### ISSUE THREAD

**Issue by crawford** [coreos/locksmith#78]
It should be possible to specify a maintenance window during which locksmith is allowed to reboot. I imagine this setting will be additive to the reboot strategy (i.e. when using etcd-lock and a maintenance window, a machine can only reboot if it is within the window and has a reboot lock).

**Comment by mischief** [comment]
some questions to be answered..
* how is the maintenance window configured?
* how is the maintenance window specified? (e.g. what syntax in the conf)

**Comment by marineam** [comment]
To make it simple to users we should support setting a window as a "start" and "end" time. The time format may be "HH:MM" or "Day HH:MM". A nightly window could be defined as:

start="23:00" end="03:00"

a weekly window would be:

start="Sat 23:00" end="Sun 03:00"

For sanity's sake we should not support multiple windows or more advanced settings. If required we could expand this later, possibly adopting systemd's format. The above examples are compatible with systemd's format.

These values could be provided as arguments or env vars to locksmithd but I probably favor something like `REBOOT_WINDOW_START=` and `REBOOT_WINDOW_END=` in /etc/coreos/update.conf

As a side note we discovered: Go's time.Parse does *not* support parsing day of the week, it allows the field to exist in format strings but simply ignores it.
