### ISSUE TITLE
"Unlocking old locks failed: error setting up lock" in log. Underlying cause is lost.

### ISSUE THREAD

**Issue by jcheroske** [coreos/locksmith#81]
I'm getting log entries like the following:

`locksmithd[502]: Unlocking old locks failed: error setting up lock. Retrying in 5m0s.`

Looking at the daemon.go, this error is emerging from the following function:

```
func setupLock() (lck *lock.Lock, err error) {
	elc, err := getClient()
	if err != nil {
		return nil, fmt.Errorf("Error initializing etcd client: %v", err)
	}

	mID := machineid.MachineID("/")
	if mID == "" {
		return nil, fmt.Errorf("Cannot read machine-id")
	}

	lck = lock.New(mID, elc)

	return lck, nil
}
```

But the calling function is discarding the error and adding it's own message instead:

```
lck, err := setupLock()
if err != nil {
  reason = "error setting up lock"
  break
}
```

Can you include information about the underlying cause in the log?  Thank you!

**Comment by mischief** [comment]
@jcheroske this error is likely locksmithd being unable to talk to etcd. the fix just committed will be in the next alpha. thanks for reporting.
