### ISSUE TITLE
availability condition for unlocking

### ISSUE THREAD

**Issue by joshk0** [coreos/locksmith#88]
I would like to use locksmithd to auto update my CoreOS instances, but on a subset of my instances I have a service that takes a very long time to start up. I would like the reboot lock to be released only when this service has come up, and I can define this using a command line / shell script. What would work is an argument to locksmithd that allows me to define this script, and logic that will not release the lock (and complain loudly about why it's not releasing the lock) until this script exits 0.

**Comment by jonboulle** [comment]
Rather than coding this into locksmith, you should be able to achieve the
same using systemd unit files. For example add a dependency to
locksmith.service on either the service file of your service itself or on a
helper service that executes whatever health check you need. Does that make
sense?

**Comment by joshk0** [comment]
So are you saying that my foo.service should have Before=locksmith.service? I'll try that and get back. Thanks. :)
